[tool.poetry]
name = "destiny"
version = "0.1.0"
description = ""
authors = ["Hajime Fujita <hajime.fujita@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
